version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    command: pnpm dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
      S3_URL: ${S3_URL}
      NEXT_PUBLIC_S3_BUCKET: ${S3_BUCKET}
      NEXT_PUBLIC_S3_URL: ${S3_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    depends_on:
      - db
      - s3
    network_mode: host
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    network_mode: host
    volumes:
      - pgdata:/var/lib/postgresql/data

  s3:
    image: adobe/s3mock
    environment:
      initialBuckets: ${S3_BUCKET}
      root: /data
      retainFilesOnExit: true
    network_mode: host
    volumes:
      - uploaddata:/data:cached

volumes:
  pgdata:
  uploaddata:
