import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import Header from "@/core/components/Header";
import AppContext from "@/core/context/AppContext";
import AuthProvider from "@/core/context/AuthContext";
import "@/styles/globals.css";
import { TRPCReactProvider } from "@/trpc/react";

import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Store",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <AuthProvider session={session}>
            <div>
              <Header />
              <main className="flex flex-col px-4 md:px-36 py-8">
                <AppContext>{children}</AppContext>
              </main>
            </div>
          </AuthProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
